<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\VSlices.Work\VSlices.Work.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="VSlices.EntityFrameworkCore.Functional" Version="0.1.0" />
  </ItemGroup>
</Project>
