<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.11" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\VSlices.Domain\VSlices.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="LanguageExt" />
		<Using Include="LanguageExt.Prelude" Static="true" />

		<Using Include="VSlices" />
		<Using Include="VSlices.Monads" />
		<Using Include="VSlices.Arrows" />
		<Using Include="VSlices.Domain.Traits" />
		<Using Include="VSlices.VSlicesDomainPrelude" Static="true" />
	</ItemGroup>

</Project>
