<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\VSlices.Domain\VSlices.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="LanguageExt" />
		<Using Include="LanguageExt.Common" />
		<Using Include="LanguageExt.Traits" />
		<Using Include="LanguageExt.Effects" />
		<Using Include="LanguageExt.Pretty" />
		<Using Include="LanguageExt.Traits.Domain" />

		<Using Include="LanguageExt.Prelude" Static="true" />

	</ItemGroup>

</Project>
